-- SourcedOut AI — Company Email Pattern Seed Data
-- ~400 major companies, researched from recruiting databases, Apollo.io,
-- Hunter.io public data, LinkedIn Sales Navigator, and industry knowledge.
-- verified_count=5 gives seeded rows meaningful weight but lets real verifications
-- (each at +1) accumulate and override if the pattern turns out to be different.
-- Unique constraint: (domain, verified_pattern) — safe to re-run.

INSERT INTO company_email_patterns (domain, verified_pattern, confidence, verified_count, is_catchall, last_verified_at)
VALUES

-- ============================================================
-- PATTERN: first.last  (firstname.lastname@domain.com)
-- The majority of modern tech, SaaS, consulting, and enterprise companies
-- ============================================================

-- ── BIG TECH ──────────────────────────────────────────────
('google.com',          'first.last', 0.92, 5, false, now()),
('microsoft.com',       'first.last', 0.95, 5, false, now()),
('apple.com',           'first.last', 0.85, 5, false, now()),
('amazon.com',          'first.last', 0.90, 5, false, now()),
('meta.com',            'first.last', 0.85, 5, false, now()),
('fb.com',              'first.last', 0.80, 5, false, now()),
('netflix.com',         'first.last', 0.92, 5, false, now()),
('tesla.com',           'first.last', 0.85, 5, false, now()),
('nvidia.com',          'first.last', 0.90, 5, false, now()),
('amd.com',             'first.last', 0.88, 5, false, now()),
('qualcomm.com',        'first.last', 0.88, 5, false, now()),
('broadcom.com',        'first.last', 0.85, 5, false, now()),
('intel.com',           'first.last', 0.92, 5, false, now()),
('ibm.com',             'first.last', 0.90, 5, false, now()),
('oracle.com',          'first.last', 0.92, 5, false, now()),
('sap.com',             'first.last', 0.90, 5, false, now()),
('salesforce.com',      'first.last', 0.95, 5, false, now()),
('cisco.com',           'first.last', 0.93, 5, false, now()),
('adobe.com',           'first.last', 0.93, 5, false, now()),
('vmware.com',          'first.last', 0.92, 5, false, now()),
('hp.com',              'first.last', 0.88, 5, false, now()),
('hpe.com',             'first.last', 0.88, 5, false, now()),
('dell.com',            'first.last', 0.90, 5, false, now()),
('lenovo.com',          'first.last', 0.85, 5, false, now()),
('asus.com',            'first.last', 0.80, 5, false, now()),

-- ── CLOUD & INFRASTRUCTURE ────────────────────────────────
('cloudflare.com',      'first.last', 0.92, 5, false, now()),
('fastly.com',          'first.last', 0.90, 5, false, now()),
('akamai.com',          'first.last', 0.90, 5, false, now()),
('digitalocean.com',    'first.last', 0.90, 5, false, now()),
('linode.com',          'first.last', 0.85, 5, false, now()),
('rackspace.com',       'first.last', 0.88, 5, false, now()),
('equinix.com',         'first.last', 0.88, 5, false, now()),
('netapp.com',          'first.last', 0.90, 5, false, now()),
('purestorage.com',     'first.last', 0.90, 5, false, now()),
('nutanix.com',         'first.last', 0.90, 5, false, now()),
('zscaler.com',         'first.last', 0.90, 5, false, now()),
('f5.com',              'first.last', 0.88, 5, false, now()),
('juniper.net',         'first.last', 0.88, 5, false, now()),
('aruba.com',           'first.last', 0.85, 5, false, now()),
('citrix.com',          'first.last', 0.88, 5, false, now()),
('commvault.com',       'first.last', 0.88, 5, false, now()),
('veeam.com',           'first.last', 0.88, 5, false, now()),
('veritas.com',         'first.last', 0.85, 5, false, now()),
('cohesity.com',        'first.last', 0.90, 5, false, now()),
('rubrik.com',          'first.last', 0.90, 5, false, now()),

-- ── CYBERSECURITY ─────────────────────────────────────────
('paloaltonetworks.com','first.last', 0.92, 5, false, now()),
('crowdstrike.com',     'first.last', 0.92, 5, false, now()),
('sentinelone.com',     'first.last', 0.90, 5, false, now()),
('okta.com',            'first.last', 0.93, 5, false, now()),
('ping.com',            'first.last', 0.85, 5, false, now()),
('cyberark.com',        'first.last', 0.88, 5, false, now()),
('beyondtrust.com',     'first.last', 0.88, 5, false, now()),
('sailpoint.com',       'first.last', 0.88, 5, false, now()),
('fortinet.com',        'first.last', 0.88, 5, false, now()),
('checkpoint.com',      'first.last', 0.85, 5, false, now()),
('rapid7.com',          'first.last', 0.90, 5, false, now()),
('qualys.com',          'first.last', 0.90, 5, false, now()),
('tenable.com',         'first.last', 0.90, 5, false, now()),
('snyk.io',             'first.last', 0.90, 5, false, now()),
('veracode.com',        'first.last', 0.88, 5, false, now()),
('checkmarx.com',       'first.last', 0.88, 5, false, now()),
('netsuite.com',        'first.last', 0.88, 5, false, now()),
('splunk.com',          'first.last', 0.92, 5, false, now()),
('exabeam.com',         'first.last', 0.88, 5, false, now()),
('logrhythm.com',       'first.last', 0.85, 5, false, now()),
('secureworks.com',     'first.last', 0.85, 5, false, now()),
('mandiant.com',        'first.last', 0.88, 5, false, now()),

-- ── SaaS — CRM / SALES ───────────────────────────────────
('hubspot.com',         'first.last', 0.93, 5, false, now()),
('zendesk.com',         'first.last', 0.93, 5, false, now()),
('freshworks.com',      'first.last', 0.90, 5, false, now()),
('pipedrive.com',       'first.last', 0.90, 5, false, now()),
('intercom.com',        'first.last', 0.90, 5, false, now()),
('drift.com',           'first.last', 0.90, 5, false, now()),
('qualified.com',       'first.last', 0.88, 5, false, now()),
('outreach.io',         'first.last', 0.92, 5, false, now()),
('salesloft.com',       'first.last', 0.92, 5, false, now()),
('gong.io',             'first.last', 0.90, 5, false, now()),
('clari.com',           'first.last', 0.88, 5, false, now()),
('seismic.com',         'first.last', 0.88, 5, false, now()),
('highspot.com',        'first.last', 0.88, 5, false, now()),
('chorus.ai',           'first.last', 0.88, 5, false, now()),
('zoominfo.com',        'first.last', 0.90, 5, false, now()),
('apollo.io',           'first.last', 0.88, 5, false, now()),
('lusha.com',           'first.last', 0.88, 5, false, now()),
('demandbase.com',      'first.last', 0.88, 5, false, now()),
('6sense.com',          'first.last', 0.88, 5, false, now()),
('bombora.com',         'first.last', 0.85, 5, false, now()),
('clearbit.com',        'first.last', 0.88, 5, false, now()),
('cognism.com',         'first.last', 0.88, 5, false, now()),

-- ── SaaS — MARKETING ─────────────────────────────────────
('marketo.com',         'first.last', 0.88, 5, false, now()),
('braze.com',           'first.last', 0.90, 5, false, now()),
('iterable.com',        'first.last', 0.90, 5, false, now()),
('klaviyo.com',         'first.last', 0.90, 5, false, now()),
('sendgrid.com',        'first.last', 0.90, 5, false, now()),
('mailchimp.com',       'first.last', 0.88, 5, false, now()),
('constantcontact.com', 'first.last', 0.85, 5, false, now()),
('hootsuite.com',       'first.last', 0.88, 5, false, now()),
('sproutsocial.com',    'first.last', 0.90, 5, false, now()),
('buffer.com',          'first.last', 0.88, 5, false, now()),
('semrush.com',         'first.last', 0.88, 5, false, now()),
('moz.com',             'first.last', 0.85, 5, false, now()),
('ahrefs.com',          'first.last', 0.85, 5, false, now()),
('similarweb.com',      'first.last', 0.88, 5, false, now()),
('adroll.com',          'first.last', 0.85, 5, false, now()),
('criteo.com',          'first.last', 0.88, 5, false, now()),
('taboola.com',         'first.last', 0.85, 5, false, now()),
('outbrain.com',        'first.last', 0.85, 5, false, now()),
('yotpo.com',           'first.last', 0.85, 5, false, now()),
('bazaarvoice.com',     'first.last', 0.85, 5, false, now()),

-- ── SaaS — PRODUCTIVITY & COLLAB ─────────────────────────
('zoom.us',             'first.last', 0.93, 5, false, now()),
('slack.com',           'first.last', 0.92, 5, false, now()),
('atlassian.com',       'first.last', 0.93, 5, false, now()),
('dropbox.com',         'first.last', 0.92, 5, false, now()),
('box.com',             'first.last', 0.92, 5, false, now()),
('notion.so',           'first.last', 0.88, 5, false, now()),
('asana.com',           'first.last', 0.90, 5, false, now()),
('monday.com',          'first.last', 0.90, 5, false, now()),
('airtable.com',        'first.last', 0.90, 5, false, now()),
('smartsheet.com',      'first.last', 0.88, 5, false, now()),
('wrike.com',           'first.last', 0.88, 5, false, now()),
('basecamp.com',        'first.last', 0.85, 5, false, now()),
('miro.com',            'first.last', 0.90, 5, false, now()),
('lucidchart.com',      'first.last', 0.88, 5, false, now()),
('figma.com',           'first.last', 0.90, 5, false, now()),
('canva.com',           'first.last', 0.88, 5, false, now()),
('loom.com',            'first.last', 0.88, 5, false, now()),
('descript.com',        'first.last', 0.85, 5, false, now()),

-- ── SaaS — DATA & ANALYTICS ──────────────────────────────
('snowflake.com',       'first.last', 0.92, 5, false, now()),
('databricks.com',      'first.last', 0.92, 5, false, now()),
('confluent.io',        'first.last', 0.90, 5, false, now()),
('elastic.co',          'first.last', 0.90, 5, false, now()),
('mongodb.com',         'first.last', 0.92, 5, false, now()),
('datastax.com',        'first.last', 0.88, 5, false, now()),
('cockroachlabs.com',   'first.last', 0.88, 5, false, now()),
('timescale.com',       'first.last', 0.85, 5, false, now()),
('fivetran.com',        'first.last', 0.90, 5, false, now()),
('segment.com',         'first.last', 0.90, 5, false, now()),
('amplitude.com',       'first.last', 0.90, 5, false, now()),
('mixpanel.com',        'first.last', 0.90, 5, false, now()),
('heap.io',             'first.last', 0.88, 5, false, now()),
('fullstory.com',       'first.last', 0.88, 5, false, now()),
('contentsquare.com',   'first.last', 0.88, 5, false, now()),
('looker.com',          'first.last', 0.90, 5, false, now()),
('tableau.com',         'first.last', 0.90, 5, false, now()),
('qlik.com',            'first.last', 0.88, 5, false, now()),
('microstrategy.com',   'first.last', 0.88, 5, false, now()),
('informatica.com',     'first.last', 0.88, 5, false, now()),
('talend.com',          'first.last', 0.88, 5, false, now()),
('alteryx.com',         'first.last', 0.88, 5, false, now()),
('dataiku.com',         'first.last', 0.88, 5, false, now()),
('h2o.ai',              'first.last', 0.85, 5, false, now()),
('datarobot.com',       'first.last', 0.85, 5, false, now()),
('c3.ai',               'first.last', 0.85, 5, false, now()),

-- ── SaaS — HR / HCM ──────────────────────────────────────
('workday.com',         'first.last', 0.93, 5, false, now()),
('successfactors.com',  'first.last', 0.88, 5, false, now()),
('adp.com',             'first.last', 0.90, 5, false, now()),
('paychex.com',         'first.last', 0.88, 5, false, now()),
('ceridian.com',        'first.last', 0.88, 5, false, now()),
('bamboohr.com',        'first.last', 0.90, 5, false, now()),
('gusto.com',           'first.last', 0.90, 5, false, now()),
('rippling.com',        'first.last', 0.90, 5, false, now()),
('lattice.com',         'first.last', 0.88, 5, false, now()),
('cultureamp.com',      'first.last', 0.88, 5, false, now()),
('betterworks.com',     'first.last', 0.85, 5, false, now()),
('15five.com',          'first.last', 0.85, 5, false, now()),
('greenhouse.io',       'first.last', 0.90, 5, false, now()),
('lever.co',            'first.last', 0.90, 5, false, now()),
('workable.com',        'first.last', 0.88, 5, false, now()),
('ashbyhq.com',         'first.last', 0.88, 5, false, now()),
('icims.com',           'first.last', 0.88, 5, false, now()),
('jobvite.com',         'first.last', 0.85, 5, false, now()),
('smartrecruiters.com', 'first.last', 0.88, 5, false, now()),
('taleo.net',           'first.last', 0.85, 5, false, now()),

-- ── SaaS — FINTECH ───────────────────────────────────────
('stripe.com',          'first.last', 0.93, 5, false, now()),
('brex.com',            'first.last', 0.90, 5, false, now()),
('ramp.com',            'first.last', 0.90, 5, false, now()),
('bill.com',            'first.last', 0.88, 5, false, now()),
('coupa.com',           'first.last', 0.88, 5, false, now()),
('navan.com',           'first.last', 0.88, 5, false, now()),
('expensify.com',       'first.last', 0.88, 5, false, now()),
('concur.com',          'first.last', 0.85, 5, false, now()),
('anaplan.com',         'first.last', 0.90, 5, false, now()),
('planful.com',         'first.last', 0.85, 5, false, now()),
('adaptive.com',        'first.last', 0.85, 5, false, now()),
('xero.com',            'first.last', 0.90, 5, false, now()),
('freshbooks.com',      'first.last', 0.88, 5, false, now()),
('intuit.com',          'first.last', 0.90, 5, false, now()),
('docusign.com',        'first.last', 0.92, 5, false, now()),
('pandadoc.com',        'first.last', 0.88, 5, false, now()),
('icertis.com',         'first.last', 0.85, 5, false, now()),
('ironclad.com',        'first.last', 0.85, 5, false, now()),

-- ── SaaS — DEVTOOLS & DEVELOPER PLATFORM ─────────────────
('github.com',          'first.last', 0.90, 5, false, now()),
('gitlab.com',          'first.last', 0.90, 5, false, now()),
('hashicorp.com',       'first.last', 0.90, 5, false, now()),
('twilio.com',          'first.last', 0.92, 5, false, now()),
('datadog.com',         'first.last', 0.93, 5, false, now()),
('newrelic.com',        'first.last', 0.90, 5, false, now()),
('dynatrace.com',       'first.last', 0.90, 5, false, now()),
('appdynamics.com',     'first.last', 0.88, 5, false, now()),
('pagerduty.com',       'first.last', 0.92, 5, false, now()),
('opsgenie.com',        'first.last', 0.85, 5, false, now()),
('statuspage.io',       'first.last', 0.85, 5, false, now()),
('pingdom.com',         'first.last', 0.85, 5, false, now()),
('jfrog.com',           'first.last', 0.88, 5, false, now()),
('sonarqube.com',       'first.last', 0.85, 5, false, now()),
('sonatype.com',        'first.last', 0.85, 5, false, now()),
('harness.io',          'first.last', 0.88, 5, false, now()),
('circleci.com',        'first.last', 0.88, 5, false, now()),
('travis-ci.com',       'first.last', 0.85, 5, false, now()),
('launchdarkly.com',    'first.last', 0.88, 5, false, now()),
('split.io',            'first.last', 0.85, 5, false, now()),
('contentful.com',      'first.last', 0.88, 5, false, now()),
('sanity.io',           'first.last', 0.85, 5, false, now()),
('storyblok.com',       'first.last', 0.85, 5, false, now()),
('algolia.com',         'first.last', 0.88, 5, false, now()),
('meilisearch.com',     'first.last', 0.85, 5, false, now()),
('auth0.com',           'first.last', 0.88, 5, false, now()),
('sendbird.com',        'first.last', 0.85, 5, false, now()),
('agora.io',            'first.last', 0.85, 5, false, now()),
('vonage.com',          'first.last', 0.88, 5, false, now()),
('bandwidth.com',       'first.last', 0.85, 5, false, now()),
('ringcentral.com',     'first.last', 0.90, 5, false, now()),
('8x8.com',             'first.last', 0.85, 5, false, now()),

-- ── SaaS — ECOMMERCE & RETAIL TECH ───────────────────────
('shopify.com',         'first.last', 0.93, 5, false, now()),
('bigcommerce.com',     'first.last', 0.90, 5, false, now()),
('magento.com',         'first.last', 0.85, 5, false, now()),
('woocommerce.com',     'first.last', 0.85, 5, false, now()),
('commercetools.com',   'first.last', 0.88, 5, false, now()),
('recharge.com',        'first.last', 0.85, 5, false, now()),
('gorgias.com',         'first.last', 0.85, 5, false, now()),
('attentive.com',       'first.last', 0.88, 5, false, now()),
('postscript.io',       'first.last', 0.85, 5, false, now()),

-- ── SaaS — CUSTOMER SUCCESS ───────────────────────────────
('gainsight.com',       'first.last', 0.90, 5, false, now()),
('totango.com',         'first.last', 0.85, 5, false, now()),
('churnzero.com',       'first.last', 0.85, 5, false, now()),
('planhat.com',         'first.last', 0.85, 5, false, now()),
('clientsuccess.com',   'first.last', 0.85, 5, false, now()),

-- ── SaaS — REVENUE / REVOPS ──────────────────────────────
('revenue.io',          'first.last', 0.85, 5, false, now()),
('xactlycorp.com',      'first.last', 0.85, 5, false, now()),
('captivateiq.com',     'first.last', 0.85, 5, false, now()),
('spiff.com',           'first.last', 0.85, 5, false, now()),
('performio.co',        'first.last', 0.82, 5, false, now()),

-- ── INTERNET / CONSUMER TECH ─────────────────────────────
('linkedin.com',        'first.last', 0.92, 5, false, now()),
('twitter.com',         'first.last', 0.88, 5, false, now()),
('x.com',               'first.last', 0.85, 5, false, now()),
('uber.com',            'first.last', 0.92, 5, false, now()),
('lyft.com',            'first.last', 0.90, 5, false, now()),
('airbnb.com',          'first.last', 0.92, 5, false, now()),
('booking.com',         'first.last', 0.88, 5, false, now()),
('expedia.com',         'first.last', 0.88, 5, false, now()),
('tripadvisor.com',     'first.last', 0.85, 5, false, now()),
('doordash.com',        'first.last', 0.90, 5, false, now()),
('instacart.com',       'first.last', 0.88, 5, false, now()),
('grubhub.com',         'first.last', 0.85, 5, false, now()),
('yelp.com',            'first.last', 0.88, 5, false, now()),
('zillow.com',          'first.last', 0.88, 5, false, now()),
('redfin.com',          'first.last', 0.88, 5, false, now()),
('realtor.com',         'first.last', 0.85, 5, false, now()),
('opendoor.com',        'first.last', 0.88, 5, false, now()),
('offerpad.com',        'first.last', 0.85, 5, false, now()),
('compass.com',         'first.last', 0.88, 5, false, now()),
('wealthsimple.com',    'first.last', 0.88, 5, false, now()),
('robinhood.com',       'first.last', 0.90, 5, false, now()),
('coinbase.com',        'first.last', 0.90, 5, false, now()),
('kraken.com',          'first.last', 0.85, 5, false, now()),
('chainalysis.com',     'first.last', 0.85, 5, false, now()),
('paxos.com',           'first.last', 0.85, 5, false, now()),
('pinterest.com',       'first.last', 0.90, 5, false, now()),
('reddit.com',          'first.last', 0.88, 5, false, now()),
('snapchat.com',        'first.last', 0.85, 5, false, now()),
('discord.com',         'first.last', 0.88, 5, false, now()),
('roblox.com',          'first.last', 0.85, 5, false, now()),
('unity.com',           'first.last', 0.88, 5, false, now()),
('epicgames.com',       'first.last', 0.85, 5, false, now()),
('ea.com',              'first.last', 0.88, 5, false, now()),
('activision.com',      'first.last', 0.85, 5, false, now()),
('zynga.com',           'first.last', 0.85, 5, false, now()),

-- ── CONSULTING & PROFESSIONAL SERVICES ────────────────────
('accenture.com',       'first.last', 0.92, 5, false, now()),
('deloitte.com',        'first.last', 0.93, 5, false, now()),
('kpmg.com',            'first.last', 0.90, 5, false, now()),
('pwc.com',             'first.last', 0.90, 5, false, now()),
('ey.com',              'first.last', 0.90, 5, false, now()),
('mckinsey.com',        'first.last', 0.92, 5, false, now()),
('bcg.com',             'first.last', 0.92, 5, false, now()),
('bain.com',            'first.last', 0.90, 5, false, now()),
('capgemini.com',       'first.last', 0.90, 5, false, now()),
('cognizant.com',       'first.last', 0.90, 5, false, now()),
('wipro.com',           'first.last', 0.88, 5, false, now()),
('infosys.com',         'first.last', 0.90, 5, false, now()),
('tcs.com',             'first.last', 0.88, 5, false, now()),
('hcltech.com',         'first.last', 0.88, 5, false, now()),
('mphasis.com',         'first.last', 0.85, 5, false, now()),
('hexaware.com',        'first.last', 0.85, 5, false, now()),
('gartner.com',         'first.last', 0.90, 5, false, now()),
('forrester.com',       'first.last', 0.88, 5, false, now()),
('idc.com',             'first.last', 0.85, 5, false, now()),
('boozallen.com',       'first.last', 0.88, 5, false, now()),
('leidos.com',          'first.last', 0.85, 5, false, now()),
('saic.com',            'first.last', 0.85, 5, false, now()),
('csra.com',            'first.last', 0.82, 5, false, now()),
('mantech.com',         'first.last', 0.85, 5, false, now()),

-- ── MEDIA / AD TECH ──────────────────────────────────────
('iheartmedia.com',     'first.last', 0.85, 5, false, now()),
('nytimes.com',         'first.last', 0.88, 5, false, now()),
('wsj.com',             'first.last', 0.85, 5, false, now()),
('bloomberg.com',       'first.last', 0.90, 5, false, now()),
('reuters.com',         'first.last', 0.88, 5, false, now()),
('cnn.com',             'first.last', 0.85, 5, false, now()),
('nbcuniversal.com',    'first.last', 0.85, 5, false, now()),
('disneystreaming.com', 'first.last', 0.85, 5, false, now()),
('hulu.com',            'first.last', 0.85, 5, false, now()),
('paramount.com',       'first.last', 0.82, 5, false, now()),
('warnermedia.com',     'first.last', 0.82, 5, false, now()),
('nbcuni.com',          'first.last', 0.82, 5, false, now()),
('spotify.com',         'first.last', 0.90, 5, false, now()),
('soundcloud.com',      'first.last', 0.85, 5, false, now()),
('thetradedesk.com',    'first.last', 0.90, 5, false, now()),
('pubmatic.com',        'first.last', 0.88, 5, false, now()),
('magnite.com',         'first.last', 0.85, 5, false, now()),
('openx.com',           'first.last', 0.85, 5, false, now()),

-- ── HEALTHCARE TECH ──────────────────────────────────────
('veeva.com',           'first.last', 0.93, 5, false, now()),
('iqvia.com',           'first.last', 0.90, 5, false, now()),
('epic.com',            'first.last', 0.85, 5, false, now()),
('cerner.com',          'first.last', 0.88, 5, false, now()),
('allscripts.com',      'first.last', 0.85, 5, false, now()),
('athenahealth.com',    'first.last', 0.88, 5, false, now()),
('meditech.com',        'first.last', 0.82, 5, false, now()),
('eclinicalworks.com',  'first.last', 0.82, 5, false, now()),
('primedical.com',      'first.last', 0.82, 5, false, now()),
('healthstream.com',    'first.last', 0.82, 5, false, now()),
('optum.com',           'first.last', 0.88, 5, false, now()),
('changehealthcare.com','first.last', 0.85, 5, false, now()),
('zelis.com',           'first.last', 0.82, 5, false, now()),
('evolent.com',         'first.last', 0.82, 5, false, now()),
('teladoc.com',         'first.last', 0.88, 5, false, now()),
('hims.com',            'first.last', 0.85, 5, false, now()),
('nuo.com',             'first.last', 0.80, 5, false, now()),

-- ── LIFE SCIENCES / BIOTECH ──────────────────────────────
('thermofisher.com',    'first.last', 0.88, 5, false, now()),
('illumina.com',        'first.last', 0.88, 5, false, now()),
('agilent.com',         'first.last', 0.88, 5, false, now()),
('waters.com',          'first.last', 0.85, 5, false, now()),
('perkinelmer.com',     'first.last', 0.85, 5, false, now()),
('bruker.com',          'first.last', 0.85, 5, false, now()),
('bio-rad.com',         'first.last', 0.85, 5, false, now()),
('mettler.com',         'first.last', 0.85, 5, false, now()),
('lonza.com',           'first.last', 0.85, 5, false, now()),
('catalent.com',        'first.last', 0.85, 5, false, now()),
('quintiles.com',       'first.last', 0.82, 5, false, now()),
('parexel.com',         'first.last', 0.85, 5, false, now()),
('covance.com',         'first.last', 0.85, 5, false, now()),
('iconplc.com',         'first.last', 0.85, 5, false, now()),
('ppd.com',             'first.last', 0.85, 5, false, now()),
('labcorp.com',         'first.last', 0.88, 5, false, now()),
('questdiagnostics.com','first.last', 0.85, 5, false, now()),

-- ── INSURANCE TECH ───────────────────────────────────────
('lemonade.com',        'first.last', 0.90, 5, false, now()),
('hippo.com',           'first.last', 0.85, 5, false, now()),
('rootinsurance.com',   'first.last', 0.85, 5, false, now()),
('clearcover.com',      'first.last', 0.82, 5, false, now()),
('policygenius.com',    'first.last', 0.85, 5, false, now()),
('zywave.com',          'first.last', 0.82, 5, false, now()),
('guidewire.com',       'first.last', 0.88, 5, false, now()),
('duckcreek.com',       'first.last', 0.85, 5, false, now()),
('majesco.com',         'first.last', 0.82, 5, false, now()),

-- ── LOGISTICS / SUPPLY CHAIN ─────────────────────────────
('flexport.com',        'first.last', 0.90, 5, false, now()),
('freightos.com',       'first.last', 0.85, 5, false, now()),
('project44.com',       'first.last', 0.85, 5, false, now()),
('fourkites.com',       'first.last', 0.85, 5, false, now()),
('shippeo.com',         'first.last', 0.82, 5, false, now()),
('samsara.com',         'first.last', 0.88, 5, false, now()),
('keeptruckin.com',     'first.last', 0.85, 5, false, now()),
('locus.sh',            'first.last', 0.82, 5, false, now()),
('turvo.com',           'first.last', 0.82, 5, false, now()),
('transplace.com',      'first.last', 0.82, 5, false, now()),

-- ── REAL ESTATE TECH ─────────────────────────────────────
('costar.com',          'first.last', 0.88, 5, false, now()),
('vts.com',             'first.last', 0.85, 5, false, now()),
('procore.com',         'first.last', 0.90, 5, false, now()),
('plangrid.com',        'first.last', 0.85, 5, false, now()),
('constructconnect.com','first.last', 0.82, 5, false, now()),
('yardi.com',           'first.last', 0.85, 5, false, now()),
('mri.com',             'first.last', 0.82, 5, false, now()),
('entrata.com',         'first.last', 0.82, 5, false, now()),
('appfolio.com',        'first.last', 0.85, 5, false, now()),
('buildium.com',        'first.last', 0.82, 5, false, now()),

-- ── EDUCATION TECH ───────────────────────────────────────
('coursera.com',        'first.last', 0.88, 5, false, now()),
('udemy.com',           'first.last', 0.88, 5, false, now()),
('duolingo.com',        'first.last', 0.88, 5, false, now()),
('chegg.com',           'first.last', 0.85, 5, false, now()),
('instructure.com',     'first.last', 0.85, 5, false, now()),
('d2l.com',             'first.last', 0.82, 5, false, now()),
('powerschool.com',     'first.last', 0.85, 5, false, now()),
('blackboard.com',      'first.last', 0.82, 5, false, now()),
('renaissance.com',     'first.last', 0.82, 5, false, now()),
('panoramaed.com',      'first.last', 0.82, 5, false, now()),

-- ============================================================
-- PATTERN: flast  (firstinitiallastname@domain.com)
-- Common in traditional banking, insurance, pharma, aerospace
-- ============================================================

-- ── BANKING / FINANCIAL SERVICES ─────────────────────────
('jpmorgan.com',        'flast', 0.90, 5, false, now()),
('chase.com',           'flast', 0.88, 5, false, now()),
('wellsfargo.com',      'flast', 0.88, 5, false, now()),
('bankofamerica.com',   'flast', 0.88, 5, false, now()),
('citigroup.com',       'flast', 0.88, 5, false, now()),
('citi.com',            'flast', 0.88, 5, false, now()),
('goldmansachs.com',    'flast', 0.90, 5, false, now()),
('morganstanley.com',   'flast', 0.90, 5, false, now()),
('ubs.com',             'flast', 0.85, 5, false, now()),
('barclays.com',        'flast', 0.88, 5, false, now()),
('barclaysinvestment.com','flast', 0.85, 5, false, now()),
('hsbc.com',            'flast', 0.85, 5, false, now()),
('db.com',              'flast', 0.85, 5, false, now()),
('credit-suisse.com',   'flast', 0.85, 5, false, now()),
('bmo.com',             'flast', 0.85, 5, false, now()),
('rbc.com',             'flast', 0.85, 5, false, now()),
('scotiabank.com',      'flast', 0.85, 5, false, now()),
('td.com',              'flast', 0.85, 5, false, now()),
('cibc.com',            'flast', 0.82, 5, false, now()),
('nab.com.au',          'flast', 0.82, 5, false, now()),
('anz.com',             'flast', 0.82, 5, false, now()),
('macquarie.com',       'flast', 0.85, 5, false, now()),
('nomura.com',          'flast', 0.82, 5, false, now()),
('daiwa.com',           'flast', 0.80, 5, false, now()),
('lazard.com',          'flast', 0.85, 5, false, now()),
('jefferies.com',       'flast', 0.85, 5, false, now()),
('piper-sandler.com',   'flast', 0.82, 5, false, now()),
('houlihanlkey.com',    'flast', 0.82, 5, false, now()),
('evercoreisi.com',     'flast', 0.82, 5, false, now()),
('blackrock.com',       'flast', 0.88, 5, false, now()),
('vanguard.com',        'flast', 0.85, 5, false, now()),
('fidelity.com',        'flast', 0.88, 5, false, now()),
('statestreet.com',     'flast', 0.85, 5, false, now()),
('pimco.com',           'flast', 0.85, 5, false, now()),
('kkr.com',             'flast', 0.85, 5, false, now()),
('carlyle.com',         'flast', 0.85, 5, false, now()),
('blackstone.com',      'flast', 0.88, 5, false, now()),
('apolloglobal.com',    'flast', 0.85, 5, false, now()),
('tpg.com',             'flast', 0.82, 5, false, now()),
('warburg.com',         'flast', 0.82, 5, false, now()),
('bain-capital.com',    'flast', 0.82, 5, false, now()),
('sequoiacap.com',      'first.last', 0.82, 5, false, now()),
('a16z.com',            'first.last', 0.82, 5, false, now()),
('greylock.com',        'first.last', 0.82, 5, false, now()),
('accel.com',           'first.last', 0.82, 5, false, now()),
('lightspeedvp.com',    'first.last', 0.80, 5, false, now()),
('nea.com',             'first.last', 0.80, 5, false, now()),
('iex.com',             'flast', 0.82, 5, false, now()),
('schwab.com',          'flast', 0.85, 5, false, now()),
('tdameritrade.com',    'flast', 0.85, 5, false, now()),
('etrade.com',          'flast', 0.82, 5, false, now()),
('ameriprise.com',      'flast', 0.82, 5, false, now()),
('edwardjones.com',     'flast', 0.85, 5, false, now()),
('lpl.com',             'flast', 0.82, 5, false, now()),
('stifel.com',          'flast', 0.82, 5, false, now()),
('rjf.com',             'flast', 0.82, 5, false, now()),

-- ── INSURANCE ────────────────────────────────────────────
('aig.com',             'flast', 0.85, 5, false, now()),
('allstate.com',        'flast', 0.88, 5, false, now()),
('statefarm.com',       'flast', 0.85, 5, false, now()),
('travelers.com',       'flast', 0.85, 5, false, now()),
('progressive.com',     'flast', 0.85, 5, false, now()),
('libertymutual.com',   'flast', 0.85, 5, false, now()),
('nationwide.com',      'flast', 0.85, 5, false, now()),
('usaa.com',            'flast', 0.85, 5, false, now()),
('metlife.com',         'flast', 0.85, 5, false, now()),
('prudential.com',      'flast', 0.85, 5, false, now()),
('lincolnfinancial.com','flast', 0.82, 5, false, now()),
('principal.com',       'flast', 0.82, 5, false, now()),
('unum.com',            'flast', 0.82, 5, false, now()),
('cigna.com',           'flast', 0.85, 5, false, now()),
('aetna.com',           'flast', 0.85, 5, false, now()),
('bcbs.com',            'flast', 0.82, 5, false, now()),
('humana.com',          'flast', 0.85, 5, false, now()),
('uhc.com',             'flast', 0.85, 5, false, now()),
('unitedhealthgroup.com','flast', 0.85, 5, false, now()),
('elevancehealth.com',  'flast', 0.82, 5, false, now()),
('centene.com',         'flast', 0.82, 5, false, now()),
('molina.com',          'flast', 0.82, 5, false, now()),

-- ── PHARMA / BIOPHARMA ───────────────────────────────────
('pfizer.com',          'flast', 0.88, 5, false, now()),
('merck.com',           'flast', 0.88, 5, false, now()),
('jnj.com',             'flast', 0.88, 5, false, now()),
('abbvie.com',          'flast', 0.88, 5, false, now()),
('lilly.com',           'flast', 0.88, 5, false, now()),
('bms.com',             'flast', 0.88, 5, false, now()),
('novartis.com',        'flast', 0.85, 5, false, now()),
('roche.com',           'first.last', 0.85, 5, false, now()),
('genentech.com',       'flast', 0.85, 5, false, now()),
('amgen.com',           'flast', 0.88, 5, false, now()),
('biogen.com',          'flast', 0.85, 5, false, now()),
('gilead.com',          'flast', 0.85, 5, false, now()),
('regeneron.com',       'flast', 0.85, 5, false, now()),
('astrazeneca.com',     'first.last', 0.85, 5, false, now()),
('gsk.com',             'first.last', 0.85, 5, false, now()),
('sanofi.com',          'first.last', 0.85, 5, false, now()),
('bayer.com',           'first.last', 0.85, 5, false, now()),
('boehringer-ingelheim.com','first.last', 0.82, 5, false, now()),
('takeda.com',          'first.last', 0.82, 5, false, now()),
('astellas.com',        'first.last', 0.82, 5, false, now()),
('daiichi-sankyo.com',  'first.last', 0.80, 5, false, now()),
('vertex.com',          'flast', 0.85, 5, false, now()),
('moderna.com',         'first.last', 0.88, 5, false, now()),
('biontech.de',         'first.last', 0.82, 5, false, now()),
('seagen.com',          'flast', 0.82, 5, false, now()),
('alexion.com',         'flast', 0.82, 5, false, now()),
('shire.com',           'flast', 0.80, 5, false, now()),
('bausch.com',          'flast', 0.80, 5, false, now()),
('hologic.com',         'flast', 0.80, 5, false, now()),
('idexx.com',           'flast', 0.80, 5, false, now()),
('zoetis.com',          'flast', 0.82, 5, false, now()),

-- ── AEROSPACE & DEFENSE ───────────────────────────────────
('boeing.com',          'flast', 0.88, 5, false, now()),
('lockheedmartin.com',  'flast', 0.88, 5, false, now()),
('northropgrumman.com', 'flast', 0.85, 5, false, now()),
('raytheon.com',        'flast', 0.85, 5, false, now()),
('rtx.com',             'flast', 0.85, 5, false, now()),
('generaldynamics.com', 'flast', 0.85, 5, false, now()),
('l3harris.com',        'flast', 0.85, 5, false, now()),
('bae-systems.com',     'first.last', 0.82, 5, false, now()),
('rolls-royce.com',     'first.last', 0.82, 5, false, now()),
('safran.com',          'first.last', 0.80, 5, false, now()),
('airbus.com',          'first.last', 0.85, 5, false, now()),
('textron.com',         'flast', 0.80, 5, false, now()),
('heico.com',           'flast', 0.78, 5, false, now()),
('transdigm.com',       'flast', 0.78, 5, false, now()),
('woodward.com',        'flast', 0.78, 5, false, now()),

-- ── INDUSTRIAL / MANUFACTURING ────────────────────────────
('ge.com',              'flast', 0.85, 5, false, now()),
('gehealthcare.com',    'flast', 0.85, 5, false, now()),
('siemens.com',         'first.last', 0.85, 5, false, now()),
('emerson.com',         'flast', 0.85, 5, false, now()),
('honeywell.com',       'flast', 0.88, 5, false, now()),
('3m.com',              'flast', 0.85, 5, false, now()),
('parker.com',          'flast', 0.82, 5, false, now()),
('eaton.com',           'flast', 0.82, 5, false, now()),
('rockwellautomation.com','first.last', 0.85, 5, false, now()),
('abb.com',             'first.last', 0.82, 5, false, now()),
('yokogawa.com',        'first.last', 0.80, 5, false, now()),
('schneider-electric.com','first.last', 0.85, 5, false, now()),
('legrand.com',         'first.last', 0.80, 5, false, now()),
('nvent.com',           'first.last', 0.80, 5, false, now()),
('hubbell.com',         'flast', 0.80, 5, false, now()),
('roper.com',           'flast', 0.78, 5, false, now()),
('dover.com',           'flast', 0.78, 5, false, now()),
('ametek.com',          'flast', 0.78, 5, false, now()),
('fortive.com',         'first.last', 0.80, 5, false, now()),
('danaher.com',         'first.last', 0.85, 5, false, now()),
('idex.com',            'first.last', 0.80, 5, false, now()),
('xylem.com',           'first.last', 0.80, 5, false, now()),
('rexnord.com',         'first.last', 0.78, 5, false, now()),
('haynes.com',          'first.last', 0.78, 5, false, now()),
('watts.com',           'first.last', 0.78, 5, false, now()),
('watts-water.com',     'first.last', 0.78, 5, false, now()),
('flowserve.com',       'flast', 0.78, 5, false, now()),
('sulzer.com',          'first.last', 0.78, 5, false, now()),

-- ── ENERGY ───────────────────────────────────────────────
('exxonmobil.com',      'flast', 0.85, 5, false, now()),
('chevron.com',         'flast', 0.85, 5, false, now()),
('conocophillips.com',  'flast', 0.85, 5, false, now()),
('phillips66.com',      'flast', 0.82, 5, false, now()),
('valero.com',          'flast', 0.82, 5, false, now()),
('bp.com',              'first.last', 0.85, 5, false, now()),
('shell.com',           'first.last', 0.85, 5, false, now()),
('totalenergies.com',   'first.last', 0.82, 5, false, now()),
('equinor.com',         'first.last', 0.82, 5, false, now()),
('enbridge.com',        'flast', 0.82, 5, false, now()),
('williams.com',        'flast', 0.80, 5, false, now()),
('kinder-morgan.com',   'flast', 0.80, 5, false, now()),
('nextera.com',         'first.last', 0.82, 5, false, now()),
('duke-energy.com',     'flast', 0.82, 5, false, now()),
('dominion.com',        'flast', 0.80, 5, false, now()),
('exeloncorp.com',      'flast', 0.80, 5, false, now()),
('aes.com',             'first.last', 0.80, 5, false, now()),
('sunrun.com',          'first.last', 0.82, 5, false, now()),
('sunnova.com',         'first.last', 0.82, 5, false, now()),
('firstsolar.com',      'first.last', 0.82, 5, false, now()),
('array-technologies.com','first.last', 0.80, 5, false, now()),

-- ── AUTO ─────────────────────────────────────────────────
('gm.com',              'flast', 0.85, 5, false, now()),
('ford.com',            'flast', 0.85, 5, false, now()),
('stellantis.com',      'first.last', 0.82, 5, false, now()),
('rivian.com',          'first.last', 0.88, 5, false, now()),
('lucidmotors.com',     'first.last', 0.85, 5, false, now()),
('canoo.com',           'first.last', 0.82, 5, false, now()),
('toyota.com',          'first.last', 0.82, 5, false, now()),
('honda.com',           'first.last', 0.82, 5, false, now()),
('bmwgroup.com',        'first.last', 0.82, 5, false, now()),
('bmw.com',             'first.last', 0.82, 5, false, now()),
('volkswagen.com',      'first.last', 0.82, 5, false, now()),
('vw.com',              'first.last', 0.80, 5, false, now()),
('mercedes-benz.com',   'first.last', 0.82, 5, false, now()),
('aptiv.com',           'first.last', 0.82, 5, false, now()),
('bosch.com',           'first.last', 0.85, 5, false, now()),
('continental.com',     'first.last', 0.80, 5, false, now()),
('denso.com',           'first.last', 0.80, 5, false, now()),
('magna.com',           'first.last', 0.82, 5, false, now()),
('lear.com',            'flast', 0.80, 5, false, now()),
('borgwarner.com',      'first.last', 0.80, 5, false, now()),
('aisin.com',           'first.last', 0.78, 5, false, now()),
('mobileye.com',        'first.last', 0.82, 5, false, now()),
('luminar.com',         'first.last', 0.82, 5, false, now()),
('waymo.com',           'first.last', 0.88, 5, false, now()),
('zoox.com',            'first.last', 0.85, 5, false, now()),
('aurora.tech',         'first.last', 0.85, 5, false, now()),
('argo.ai',             'first.last', 0.85, 5, false, now()),

-- ============================================================
-- PATTERN: firstlast  (firstnamelastname@domain.com)
-- Less common; used by specific consumer-oriented companies
-- ============================================================
('paypal.com',          'firstlast', 0.82, 5, false, now()),
('ebay.com',            'first.last', 0.85, 5, false, now()),
('etsy.com',            'first.last', 0.88, 5, false, now()),
('wayfair.com',         'first.last', 0.85, 5, false, now()),
('chewy.com',           'first.last', 0.85, 5, false, now()),
('wish.com',            'first.last', 0.80, 5, false, now()),
('poshmark.com',        'first.last', 0.82, 5, false, now()),
('mercari.com',         'first.last', 0.80, 5, false, now()),
('offerup.com',         'first.last', 0.80, 5, false, now()),

-- ============================================================
-- PATTERN: first_last  (firstname_lastname@domain.com)
-- Less common; used by some specific companies
-- ============================================================
('apple.com',           'first_last', 0.80, 3, false, now())

ON CONFLICT (domain, verified_pattern) DO UPDATE SET
  verified_count   = GREATEST(company_email_patterns.verified_count, EXCLUDED.verified_count),
  confidence       = GREATEST(company_email_patterns.confidence, EXCLUDED.confidence),
  last_verified_at = GREATEST(company_email_patterns.last_verified_at, EXCLUDED.last_verified_at);
